[profile.default]
src = 'contracts'
out = 'out'

fs_permissions = [{ access = "read-write", path = "./"}]
remappings = ['@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts']

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"

[etherscan]
goerli = { key = "${GOERLI_SCAN_API_KEY}", url = "${GOERLI_ETHERSCAN_VERIFIER_URL}" }
optimism = { key = "${OPTIMISM_SCAN_API_KEY}", url = "${OPTIMISM_ETHERSCAN_VERIFIER_URL}" }